---
- name: Mettre à jour les paquets système
  apt:
    update_cache: yes

- name: Installer Docker
  apt:
    name: docker.io
    state: "{{ docker_version }}"

- name: Restreindre les permissions du socket Docker
  file:
    path: /var/run/docker.sock
    mode: '0640'
    owner: root
    group: "{{ docker_group }}"

- name: Configurer le fichier de configuration de Docker
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Redémarrer le service Docker
  notify: restart docker

