all:
  hosts:
    ubuntu:
      ansible_host: 192.168.68.121
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_become: true
      ansible_become_method: sudo

